### ISSUE TITLE
Video-based hand estimation

### ISSUE THREAD

**Issue by GFTQ** [mks0601/V2V-PoseNet_RELEASE#13]
Hi, Gyeongsik
First of all, thank you very much for your outstanding work-V2V! I just want to discuss with you other than V2V. So far, most discriminative methods performing hand estimation from single hand depth map have been conducted on Frame level, and they most struggle in  hand self-occlusion or other unseen hand joint situation. However, the actual hand estimation is mostly applied to video-level scene (continuous frame). In the case of discriminative methods,  why can we introduce the constraints of former-hand-frame to infer current hand pose? Such like RNN, LSTM. Unfortunately, I found that LSTM and RNN are only adopted in video classification, Is there any possibility that taking constraints of continuous frame into account for hand estimation. More directly, can we introduce LSTM or RNN to discriminative methods?

Look forward to your opinion.

Hopes for your replay, thanks very much.

**Comment by mks0601** [comment]
Hi, GFTQ. First of all, thank you for having interest in my research.

I also thought that using temporal information can (should) bring large performance improvement, however, I read some video segmentation and single object tracking papers and realized that isn't always true. I cannot remember the name of papers, however you can read some papers from DAVIS challenge. There are some works using LSTM for human pose estimation such as LSTM pose machine (https://arxiv.org/pdf/1712.06316.pdf). As you can see in the paper, utilizing temporal information with LSTM brings performance improvement.

However that isn't critical. Rather than that, using deeper network, utilizing multi-scale information more effectively brings larger performance improvement as in many human pose estimation papers. I think that is why people focus on other contributions instead of using temporal information modeling tools such as LSTM and other RNNs. Also, as far as I know, detection-based single object tracking papers outperformed ones trying to model temporal information better. 

Also, there are some practical issues such as comparison with previous methods (most methods are frame-based) and using state-of-the-art network architecture (most of the CV papers are focusing on improving network architecture, not modeling temporal information. So they takes a single image as input.). 

How about your opinion?

Best,
Gyeongsik Moon

**Comment by GFTQ** [comment]
Hi, Gyeongsik Moon.

I'm so sorry for no reply for a long time.

Indeed, I adpot a strategy slightly different from 'LSTM Pose Machine' to embed vanilla LSTM into V2V! Unfortunately, in my experiments, my sequential structure based LSTM seriously dragged down the accuracy of single model estimaiton. Maybe, some new kind of Recurrent Unit is my next step. The related source code i upload can be found in (https://github.com/GFTQ/V2V-PoseNet_RELEASE). Thank you again!
Best
