### ISSUE TITLE
Real-time inference on ITOP

### ISSUE THREAD

**Issue by saileshprem** [mks0601/V2V-PoseNet_RELEASE#37]
I'm trying to perform real-time inference on the ITOP dataset. I would appreciate any help in that direction.
I did load the pretrained model and run test. But do I have to use matlab/octave to visualize? If I want to run the model on a depth cam feed and visualize at the same time. Do you think this is possible and if yes, can you point me in the right direction?

**Comment by mks0601** [comment]
I think this would be possible. Create a python code which consists of some bash commands. For each frame from the cam, run my lua code and save the estimated result file in `.txt` format and use matplotlib to visualize the result. Otherwise, you can run MATLAB on the background and wait for a new `.txt` file.

**Comment by saileshprem** [comment]
Hey thanks for the quick response and I'm really interested in your research. I read through your code and your paper thoroughly and now I've got a better understanding of the pipeline. I was able to try and test it for single frames but only on ITOP's test dataset. While running on my own cam feed, I realize I would need the center values to create the 'cubic box' that contains the hand/human. So I have two questions about this,

1. Can you share the source code you used to calculate the center values for ITOP(top-view) dataset? I see that you've used deep prior++ and it has pretrained models only for hand datasets, or I would even appreciate some guidance in training deep prior ++ to calculate human centers for ITOP-topview. Or alternatively, do you think setting the center to the center of the image and the cube size to the entire image will work?

2. How do you think this model would scale for multiple people in the image? Would calculating centers be an issue in this case since humans standing close to each other will seem like a single blob to the network?

**Comment by mks0601** [comment]
1. Unfortunately, I don't have code to calculate center values right now. As you can read in the deep prior++ paper, the network is very easy to implement, so I think you can implement it. Using center of entire image would not work because model is trained from cropped cubic. Alternatively, you can use 2d human detector to get bounding box and calculate center-of-mass of depth values inside of the bounding box.

2. I think extending this work to multi-person case is straightforward. Apply human detector to get 2d human bouding box and get centers by center estimator (from deep prior++) or average of depth values inside of the box. For each cropped human, you can apply V2V-PoseNet.

**Comment by saileshprem** [comment]
1. I'll then look into the Deep prior++ paper and try to implement the network.

2. Regarding the 2d human detector, since I'm trying to do top view pose estimation, top view human detection dataset or pre-trained models are hard to find/non-existent. Since you mentioned it, are you awere of anything that already exists?

3. Since this post is about "real-time" I would appreciate your help in one more issue. I tried to time the time taken for a single image through the model and found it to be almost a second (0.85s) on a GTX 1070. On further analysis, I timed individual modules to find that the *generate_cubic_input* function consumed more than 90% of the time. On further analysis, looks like the snippet:

`coord:apply(function(x)
        i = i + 1
        if i == 1 then
            x_ = x
        elseif i == 2 then
            y_ = x
        elseif i == 3 then
            z_ = x
            cubic[z_][y_][x_] = 1
            i = 0
        end
    end)`

from the "scattering" function takes the entire time. I'm not able to decipher what exactly is happening there. Why do you think this is happening and do you think there is a way to speed it up? Because if that's possible I think the model would run at, at the least 10 fps on a decent GPU.

Thanks in advance! :)

**Comment by mks0601** [comment]
2. Sorry. I don't know. As there is no dataset for 3d depth map-based multi-person pose estimation dataset, training a model would be hard. Maybe you can train a model if you have your own dataset.

3. As written in the paper, most of the computation time is concentrated on the voxelization part like you measured. The code line tries to fill empty voxels if a point exist in the voxel. I think it can be accelerated if you use GPU computations using `scatter` operation (https://github.com/torch/torch7/blob/master/doc/tensor.md#tensor-scatterdim-index-srcval). Actualy, it's been a long time since I used lua torch7, so I cannot remember clearly. If you use more advanced framework such as TensorFlow or PyTorch, you can implement that part in a parallel way with GPU operations. Check PyTorch implementation of the V2V-PoseNet (https://github.com/dragonbook/V2V-PoseNet-pytorch).
