### ISSUE TITLE
MSRA yaw pitch calculation

### ISSUE THREAD

**Issue by cheolhwanyoo** [mks0601/V2V-PoseNet_RELEASE#51]
Hi. Thank you very much for sharing your project!
I'm trying to measure the error for the MSRA dataset over yaw, pitch angles. 

However, my dataset seems to be newer version and it is not fit to ground truth msra_angle.txt provided by awsome handpose github.   

Can you provide information how you calculate error on your paper?

Thank you.

**Comment by mks0601** [comment]
Hi, I also had that issue because I tested on newer version of MSRA dataset. I cannot clearly remember because it is a couple of years ago, but I think there is some code in awesome hand pose git that calculate angles from coordinates. Using groundtruth msra hand pose coordinates, I calculated the angles using that code and used that angles as groundtruth.

**Comment by cheolhwanyoo** [comment]
Thank you very much! i'll try it
