### ISSUE TITLE
Different Sz in Generate_cubic_input() and Discretize()

### ISSUE THREAD

**Issue by GFTQ** [mks0601/V2V-PoseNet_RELEASE#6]
HI, Thanks for your open source code. I read your code carefully and try to implement it, and i get confused in different Size in Generate_cubic_input() and Discretize(), including oringinalSz =96, CroppedSz =88, CubicSz = 250 (NYU).  There seems two kinds of 'normalize', first implenmeted in Generate_cubic_input() by "/(cubicSz/2)", and second implemented in discretize() by "/croppedSz", What is the differences among them, especially between cubicSz and orginalSz. 
Hopes for your replay, thanks very much.

**Comment by mks0601** [comment]
Hi GFTQ.

The depth map from a dataset contain entire human body and backgrounds. In order to extract hand from a depth map, most of the methods including mine draw a 3D cubic around a "reference point". This reference point can be calculated by depth thresholding follwed by center of mass computation or other more sophisticated methods (described in section 4 of my paper). The length of a edge of the 3D cubic is defined as "cubicSz" variable. 

The "originalSz" and "croppedSz" variables are for translation data augmentation. I firstly discretize the extracted hand into originalSz and randomly crop by croppedSz.

Hope this would be helpful.

**Comment by GFTQ** [comment]
Thanks very much for your quick replay.

Now, I understand what is originalSz, but I do not know whether if i miss some thing. In generate_cubic_input(), after pixel2world() and normalize(), I know the (x,y,z) of hand all are normalized to (-1,1), as you said, you first discretize the extracted hand into originalSz, why in the function dicretize(), you first convert the normalized value to croppedSz, by"str = (max_normalized - min_normalized)/croppedSz".

Thanks again

**Comment by mks0601** [comment]
Oh, my answer above is not right. I firstly discretize the extracted hand into croppedSz and pad (originalSz/2 - croppedSz/2) voxels in 3 axis (x,y,z).

**Comment by GFTQ** [comment]
What a clever design, I learned a lot，thanks very much

**Comment by mks0601** [comment]
Thanks for having interest in my research. Ask me if encounter any problem : )
